### ISSUE TITLE
Hard coded paths won't work for others

### ISSUE THREAD

**Issue by tseemann** [ksw9/mtb_variant_identification#1]
https://github.com/ksw9/mtb_variant_identification/blob/d0b8df2b43bf470290f39bd664b11e366b6735ee/scripts/filter_vcf.sh#L27-L28

Many other examples.

One solution is to have a single "config" file which has all the things

eg. `config.txt` 
```
BCFTOOLS=bcftools
REF=/path/to/h37rv.fna
etc
```
And then use them like
```
#!/bin/bash

source config.txt
$BCFTOOLS -r $REF -filter X -out foo
etc
```

**Comment by ksw9** [comment]
Thanks for the comment and sorry for the delay!
Updated as suggested.
